apiVersion: v1
kind: Service
metadata:
  name: vault-test-svc
  labels:
    app: vault
spec:
  type: LoadBalancer
  ports:
  - port: 8200
  selector:
    app: vault
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: sleyva97/vault
        ports:
        - containerPort: 8200

      - name: consul
        image: sleyva97/consul
        ports:
        - containerPort: 8500
