version: 2.0
jobs:
  "verify":
    docker:
      - image: theyorkshiredev/dockerfile-linter
    steps:
    - checkout
    - run: dockerfilelint consul/Dockerfile
    - run: dockerfilelint vault/Dockerfile
  "build":
    machine: true
    steps:
      - checkout
      - run: docker version
      - run: sudo service docker stop
      - run: curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run: docker build vault/ -t vault
      - run: docker build consul/ -t consul
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker tag vault $DOCKER_USER/vault
      - run: docker tag consul $DOCKER_USER/consul
      - run: docker push $DOCKER_USER/vault
      - run: docker push $DOCKER_USER/consul

workflows:
  version: 2
  build_and_test:
    jobs:
      - "verify"
      - "build":
          requires:
            - "verify"
          filters:
            branches:
              only: master
