version: 2.0
jobs:
  "verify":
    docker:
      - image: theyorkshiredev/dockerfile-linter
    steps:
    - checkout
    - run:
        name: lint docker files
        command: |
          dockerfilelint consul/Dockerfile
          dockerfilelint vault/Dockerfile
  "build":
    machine: true
    steps:
      - checkout
      - run:
          name: Upgrade docker
          command: |
             docker version
             sudo service docker stop
             curl -fsSL https://get.docker.com/ | sudo sh
             docker version
      - run:
          name: Build and save images
          command: |
            echo 'Building...'
            docker build vault/ -t vault
            docker build consul/ -t consul
            echo 'Saving...'
            mkdir -p docker-images
            docker save -o docker-images/vault.tar vault
            docker save -o docker-images/consul.tar consul
            echo 'Saving to cache'
      - save_cache:
          key: docker-images
          paths:
            - docker-images
  "test":
    machine: true
    steps:
    - checkout
    - run:
        name: Upgrade docker
        command: |
          printf '%s' "Installing Docker"
          curl -fsSL https://get.docker.com/ | sudo sh
          docker version
    - run:
        name: Install Docker Compose
        command: |
          set -x
          sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > ./docker-compose
          sudo chmod +x ./docker-compose
    - run:
        name: Install Vault
        command: |
          set -x
          cd /tmp
          echo Fetching Vault...
          curl -L https://releases.hashicorp.com/vault/0.9.0/vault_0.9.0_linux_amd64.zip?_ga=2.50680617.1832357802.1511677005-1273715247.1505411633 > vault.zip

          echo Installing Vault...
          sudo unzip vault.zip -d /bin/
          sudo chmod 0755 /bin/vault 
          vault --version
    - run:
        name: Stand up the Vault/Consul stack
        command: | 
          ./docker-compose up -d
    - run: ./test.sh
  "deploy":
    machine: true
    steps:
      - restore_cache:
          keys: docker-images
      - run:
          name: Docker push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            export vault_image=$(docker load < docker-images/vault.tar | tail -n1 | awk '{print $NF}')
            export consul_image=$(docker load < docker-images/consul.tar | tail -n1 | awk '{print $NF}')
            docker tag "$vault_image" $DOCKER_USER/vault
            docker tag "$consul_image" $DOCKER_USER/consul
            docker push $DOCKER_USER/vault
            docker push $DOCKER_USER/consul
workflows:
  version: 2
  build_and_test:
    jobs:
      - "verify"
      - "build":
          requires:
            - "verify"
          filters:
            branches:
              only: master
      - "test":
          requires:
            - "build"
          filters:
            branches:
              only: master
      - "deploy":
          requires:
            - build
          filters:
            branches:
              only: master
